### ISSUE TITLE
Crash ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Baynar** [OregonCore/OregonCore#1414] opened 2016-06-06 12:35 UTC
**Revision**:
3500
**Operating system**:
Windows 10
**Current behavior**: 
....crash

**Expected behavior**: 
...no crash

**Steps to reproduce the problem**:
Crash log: http://pastebin.com/fH0ddBZj

**Comment by LordUsagi** [comment] 2016-06-06 14:08
Duplicate of #1389 

Please take a quick look at our issue tracker before making another topic on the same bug.

**Closed as completed by LordUsagi** 2016-06-06 14:08 UTC

**Comment by Baynar** [comment] 2016-06-06 14:33
I Closed the other duplicate cause i saw  the unresolved db errors are the same
 but i can't find this in the bug tracker......
