### ISSUE TITLE
[Spell] Paladin Human Righteous Defense

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1295] opened 2016-02-26 06:43 UTC
**Revision**: a746d3f

**Operating system**: Windows Webserver RC2

**Current behavior**: Come to the defense of a friendly target, commanding up to 3 enemies attacking the target to attack the Paladin instead.
....

**Expected behavior**: Paladin Human spot
...

**Steps to reproduce the problem**: i dont can spot any mobs (Pala lvl70)

**Comment by LordUsagi** [comment] 2016-02-26 14:38
Duplicate of #985

**Closed as completed by LordUsagi** 2016-02-26 14:38 UTC
