### ISSUE TITLE
[crash] Aura::HandleModPossessPet

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1342] opened 2016-04-11 17:38 UTC
**Revision**: Latest

**Operating system**: Unix

**Current behavior**: Core crashes propably when using spell eye of the beast.. not sure  but it is a pet problem :P
....

**Expected behavior**: should not crash
...

**Steps to reproduce the problem**: crashdump: https://gist.github.com/dikkedeur/8486ecc0bb4971ec5d34d18801eb0642

**Comment by Zaffy** [comment] 2016-04-15 17:21
Duplicate of #1343

**Closed as completed by Zaffy** 2016-04-15 17:21 UTC
Labels: duplicate
